---
- name: Install, configure, and launch filebeat on Web VMs
  hosts: webservers
  become: true
  tasks:
    # Download and install the filebeat package from elastic.co
    - name: Download and install filebeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    # Copy the filebeat configuration
    # (/etc/ansible/roles/files/filebeat-config.yml) to the host
    # (/etc/filebeat/filebeat.yml)
    - name: Copy filebeat-config.yml to the host (/etc/filebeat/filebeat.yml)
      copy:
        src: /etc/ansible/roles/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    # Enable filebeat system module
    - name: Enable filebeat system module
      command: filebeat modules enable system

    # Setup filebeat
    - name: Setup filebeat
      command: filebeat setup

    # Enable the filebeat service
    - name: Start filebeat service
      service:
        name: filebeat
        state: started
        enabled: true
