---
- name: Install, configure, and launch filebeat on Web VMs
  hosts: webservers
  become: true
  tasks:
    # Use get_url to download the deb package
    - name: Download filebeat deb package
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
        dest: /tmp/filebeat-7.6.1-amd64.deb

    # Use dpkg to install the filebeat deb pkg
    - name: Install filebeat-7.6.1-amd64.deb
      command: dpkg -i /tmp/filebeat-7.6.1-amd64.deb

    # Copy the filebeat configuration
    # (/etc/ansible/roles/files/filebeat-config.yml) to the host
    # (/etc/filebeat/filebeat.yml)
    - name: Copy filebeat-config.yml to the host (/etc/filebeat/filebeat.yml)
      copy:
        src: /etc/ansible/roles/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    # Enable filebeat system module
    - name: Enable filebeat system module
      command: filebeat modules enable system

    # Setup filebeat
    - name: Setup filebeat
      command: filebeat setup

    # Enable the filebeat service
    - name: Start filebeat service
      command: service filebeat start
